apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: orpl8nb2m-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/orpl8nb2m-dotnet-basic-gitops