apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: orpl8nb2m-dotnet-basic
  janus-idp.io/tekton: orpl8nb2m-dotnet-basic
  backstage.io/kubernetes-id: orpl8nb2m-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: orpl8nb2m-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
